---
language: c
sudo: false
compiler:
  - gcc
  - clang
script:
  - mkdir build
  - pushd build
  - cmake ..
  - cmake --build .
  - ctest
env:
  - CODECOV_TOKEN="5f554f97-61fa-4b0d-91cd-29e9f3f426aa"

after_success:
  - pushd build
  - bash <(curl -s https://codecov.io/bash)
